source('baseparameters.R')
source('IterateSpectrum.R')
# source('plotSpectrum.R')
# source('plotBiomasstime.R')
# source('YieldCalc.R')
source('baseparameters_trimmed.R')
source('runOM.R')
require(ggplot2)
require(dplyr)
